# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED MMXISF_SOURCE_DIR)
  message(FATAL_ERROR "MMXISF_SOURCE_DIR is required")
endif()

function(read_json output relative_path)
  file(READ "${MMXISF_SOURCE_DIR}/${relative_path}" contents)
  string(JSON parsed ERROR_VARIABLE error GET "${contents}")
  if(NOT error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Invalid JSON in ${relative_path}: ${error}")
  endif()
  set(${output} "${contents}" PARENT_SCOPE)
endfunction()

read_json(specification "docs/specification-baseline.json")
read_json(matrix "docs/conformance/xisf-1.0-matrix.json")
read_json(fixture_schema "docs/fixtures/manifest.schema.json")
read_json(interop_manifest "tests/interop/manifest.json")

string(JSON specification_schema GET "${specification}" schema)
if(NOT specification_schema STREQUAL "mmxisf.specification-baseline/1.0.0")
  message(FATAL_ERROR "Unexpected specification-baseline schema")
endif()

string(JSON source_commit GET "${specification}" specification sourceCommit)
if(NOT source_commit MATCHES "^[0-9a-f][0-9a-f]+$")
  message(FATAL_ERROR "Invalid specification source commit")
endif()
string(LENGTH "${source_commit}" source_commit_length)
if(NOT source_commit_length EQUAL 40)
  message(FATAL_ERROR "Specification source commit must have 40 hex digits")
endif()

string(JSON matrix_schema GET "${matrix}" schema)
if(NOT matrix_schema STREQUAL "mmxisf.conformance-matrix/1.0.0")
  message(FATAL_ERROR "Unexpected conformance-matrix schema")
endif()

string(JSON row_count LENGTH "${matrix}" rows)
if(row_count LESS 1)
  message(FATAL_ERROR "Conformance matrix is empty")
endif()

set(ids)
math(EXPR last_row "${row_count} - 1")
foreach(index RANGE ${last_row})
  string(JSON id GET "${matrix}" rows ${index} id)
  list(FIND ids "${id}" existing_index)
  if(NOT existing_index EQUAL -1)
    message(FATAL_ERROR "Duplicate conformance id: ${id}")
  endif()
  list(APPEND ids "${id}")

  foreach(field pfi baselineDecoder)
    string(JSON status GET "${matrix}" rows ${index} ${field})
    if(NOT status MATCHES "^(REQUIRED|INSPECT_ONLY|REJECT_EXPLICITLY|DEFERRED)$")
      message(FATAL_ERROR "Invalid ${field} status for ${id}: ${status}")
    endif()
  endforeach()

  string(JSON target GET "${matrix}" rows ${index} target)
  if(NOT target MATCHES "^(0\\.[1-4]|DEFERRED)$")
    message(FATAL_ERROR "Invalid target for ${id}: ${target}")
  endif()
endforeach()

string(JSON fixture_schema_id GET "${fixture_schema}" properties schema const)
if(NOT fixture_schema_id STREQUAL "mmxisf.fixture-manifest/1.0.0")
  message(FATAL_ERROR "Unexpected fixture-manifest schema")
endif()

string(JSON interop_schema GET "${interop_manifest}" schema)
if(NOT interop_schema STREQUAL fixture_schema_id)
  message(FATAL_ERROR "Unexpected interop fixture-manifest schema")
endif()

string(JSON interop_fixture_count LENGTH "${interop_manifest}" fixtures)
if(interop_fixture_count LESS 1)
  message(FATAL_ERROR "Interop fixture manifest is empty")
endif()

set(fixture_ids)
math(EXPR last_fixture "${interop_fixture_count} - 1")
foreach(index RANGE ${last_fixture})
  string(JSON fixture_id GET "${interop_manifest}" fixtures ${index} id)
  list(FIND fixture_ids "${fixture_id}" existing_fixture_index)
  if(NOT existing_fixture_index EQUAL -1)
    message(FATAL_ERROR "Duplicate fixture id: ${fixture_id}")
  endif()
  list(APPEND fixture_ids "${fixture_id}")

  string(JSON fixture_sha GET "${interop_manifest}" fixtures ${index} sha256)
  if(NOT fixture_sha MATCHES "^[0-9a-f][0-9a-f]+$")
    message(FATAL_ERROR "Invalid SHA-256 for fixture ${fixture_id}")
  endif()
  string(LENGTH "${fixture_sha}" fixture_sha_length)
  if(NOT fixture_sha_length EQUAL 64)
    message(FATAL_ERROR "Fixture SHA-256 must have 64 hex digits: ${fixture_id}")
  endif()

  string(JSON storage_kind GET "${interop_manifest}" fixtures ${index} storage kind)
  if(NOT storage_kind MATCHES "^(GIT_LFS|GIT_TEXT|LOCAL_PRIVATE)$")
    message(FATAL_ERROR "Invalid storage kind for fixture ${fixture_id}")
  endif()
  string(JSON storage_path GET "${interop_manifest}" fixtures ${index} storage path)
  if(NOT EXISTS "${MMXISF_SOURCE_DIR}/${storage_path}")
    message(FATAL_ERROR "Fixture path does not exist: ${storage_path}")
  endif()

  string(JSON conformance_count LENGTH "${interop_manifest}" fixtures ${index} conformanceRows)
  if(conformance_count LESS 1)
    message(FATAL_ERROR "Fixture has no conformance rows: ${fixture_id}")
  endif()
  math(EXPR last_conformance "${conformance_count} - 1")
  foreach(conformance_index RANGE ${last_conformance})
    string(JSON conformance_id GET "${interop_manifest}" fixtures ${index} conformanceRows ${conformance_index})
    list(FIND ids "${conformance_id}" conformance_row_index)
    if(conformance_row_index EQUAL -1)
      message(FATAL_ERROR "Unknown conformance row ${conformance_id} for fixture ${fixture_id}")
    endif()
  endforeach()
endforeach()

set(native_validation_script
  "${MMXISF_SOURCE_DIR}/tests/pixinsight/MMXISFWriterNativeValidation.js")
set(native_validation_checksum
  "${MMXISF_SOURCE_DIR}/tests/pixinsight/MMXISFWriterNativeValidation.js.sha256")
if(NOT EXISTS "${native_validation_script}" OR
   NOT EXISTS "${native_validation_checksum}")
  message(FATAL_ERROR "Native writer validation script or checksum is missing")
endif()
file(SHA256 "${native_validation_script}" native_validation_actual_sha256)
file(READ "${native_validation_checksum}" native_validation_checksum_line)
string(STRIP "${native_validation_checksum_line}" native_validation_checksum_line)
if(NOT native_validation_checksum_line MATCHES
   "^([0-9a-f]+)  MMXISFWriterNativeValidation\\.js$")
  message(FATAL_ERROR "Invalid native writer validation checksum sidecar")
endif()
set(native_validation_expected_sha256 "${CMAKE_MATCH_1}")
if(NOT native_validation_expected_sha256 STREQUAL
   native_validation_actual_sha256)
  message(FATAL_ERROR "Native writer validation script checksum mismatch")
endif()

message(STATUS "Validated ${row_count} XISF planning rows and ${interop_fixture_count} interop fixtures")
