# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED MMXISF_BINARY_SBOM OR NOT EXISTS "${MMXISF_BINARY_SBOM}")
  message(FATAL_ERROR "MMXISF_BINARY_SBOM must name a generated SBOM")
endif()
if(NOT DEFINED MMXISF_PROJECT_VERSION)
  message(FATAL_ERROR "MMXISF_PROJECT_VERSION is required")
endif()

file(READ "${MMXISF_BINARY_SBOM}" sbom)
string(JSON spdx_version ERROR_VARIABLE parse_error GET "${sbom}" spdxVersion)
if(NOT parse_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Invalid binary SPDX JSON: ${parse_error}")
endif()
if(NOT spdx_version STREQUAL "SPDX-2.3")
  message(FATAL_ERROR "Unexpected binary SPDX version")
endif()

string(JSON package_count LENGTH "${sbom}" packages)
if(NOT package_count EQUAL 6)
  message(FATAL_ERROR "Binary SBOM must describe mmxisf and five dependencies")
endif()

set(required_packages mmxisf Expat zlib LZ4 Zstandard OpenSSL)
set(observed_packages)
math(EXPR last_package "${package_count} - 1")
foreach(index RANGE ${last_package})
  string(JSON name GET "${sbom}" packages ${index} name)
  string(JSON version GET "${sbom}" packages ${index} versionInfo)
  string(JSON license GET "${sbom}" packages ${index} licenseDeclared)
  if(version STREQUAL "" OR version STREQUAL "NOASSERTION")
    message(FATAL_ERROR "Binary SBOM has no resolved version for ${name}")
  endif()
  if(license STREQUAL "" OR license STREQUAL "NOASSERTION")
    message(FATAL_ERROR "Binary SBOM has no declared license for ${name}")
  endif()
  list(APPEND observed_packages "${name}")
  if(name STREQUAL "mmxisf" AND NOT version STREQUAL MMXISF_PROJECT_VERSION)
    message(FATAL_ERROR "Binary SBOM project version does not match CMake")
  endif()
endforeach()

foreach(required IN LISTS required_packages)
  list(FIND observed_packages "${required}" found_index)
  if(found_index EQUAL -1)
    message(FATAL_ERROR "Binary SBOM is missing ${required}")
  endif()
endforeach()

message(STATUS "Validated binary SPDX dependency versions")
