# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED MMXISF_SOURCE_DIR)
  message(FATAL_ERROR "MMXISF_SOURCE_DIR is required")
endif()

if(DEFINED MMXISF_SUPPORT_PROFILE_FILE)
  set(_profile_path "${MMXISF_SUPPORT_PROFILE_FILE}")
else()
  set(_profile_path
    "${MMXISF_SOURCE_DIR}/docs/support-profile-0.1.0.json")
endif()

if(NOT EXISTS "${_profile_path}")
  message(FATAL_ERROR "Missing support profile: ${_profile_path}")
endif()

file(READ "${_profile_path}" _profile)
string(JSON _profile_schema ERROR_VARIABLE _profile_error GET
  "${_profile}" schema)
if(NOT _profile_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Invalid support profile JSON: ${_profile_error}")
endif()
if(NOT _profile_schema STREQUAL "mmxisf.support-profile/1.0.0")
  message(FATAL_ERROR "Unexpected support-profile schema")
endif()

string(JSON _profile_id GET "${_profile}" profileId)
if(NOT _profile_id STREQUAL "STANDALONE_MONOLITHIC_0_1")
  message(FATAL_ERROR "Unexpected support profile id: ${_profile_id}")
endif()
string(JSON _profile_version GET "${_profile}" profileVersion)
if(NOT _profile_version STREQUAL "0.1.0")
  message(FATAL_ERROR "Unexpected support profile version: ${_profile_version}")
endif()

string(JSON _state GET "${_profile}" state)
string(JSON _candidate_commit GET "${_profile}" candidateCommit)
if(NOT _state MATCHES "^(PREPARED|FROZEN)$")
  message(FATAL_ERROR "Invalid support profile state: ${_state}")
endif()
if(_state STREQUAL "PREPARED" AND NOT _candidate_commit STREQUAL "")
  message(FATAL_ERROR "A PREPARED support profile cannot bind a candidate commit")
endif()
if(_state STREQUAL "FROZEN")
  if(NOT _candidate_commit MATCHES "^[0-9a-f][0-9a-f]+$")
    message(FATAL_ERROR "A FROZEN support profile requires a hexadecimal commit")
  endif()
  string(LENGTH "${_candidate_commit}" _candidate_commit_length)
  if(NOT _candidate_commit_length EQUAL 40)
    message(FATAL_ERROR "A FROZEN support profile requires a 40-digit commit")
  endif()
endif()

string(JSON _product_kind GET "${_profile}" productBoundary kind)
if(NOT _product_kind STREQUAL "REUSABLE_CPP_LIBRARY")
  message(FATAL_ERROR "Support profile must describe the reusable C++ library")
endif()
string(JSON _viewer_included GET "${_profile}" productBoundary viewerIncluded)
if(_viewer_included)
  message(FATAL_ERROR "The optional viewer cannot be part of library readiness")
endif()
string(JSON _pfi_included GET "${_profile}" productBoundary pfiAdapterIncluded)
if(_pfi_included)
  message(FATAL_ERROR "The PFI adapter cannot be part of the standalone profile")
endif()
string(JSON _transport GET "${_profile}" productBoundary transport)
if(NOT _transport STREQUAL "LOCAL_MONOLITHIC_ONLY")
  message(FATAL_ERROR "Unexpected transport boundary: ${_transport}")
endif()
string(JSON _language GET "${_profile}" productBoundary languageStandard)
if(NOT _language STREQUAL "C++20")
  message(FATAL_ERROR "Unexpected language standard: ${_language}")
endif()

string(JSON _matrix_relative_path GET "${_profile}" matrix path)
if(NOT _matrix_relative_path STREQUAL
   "docs/conformance/xisf-1.0-matrix.json")
  message(FATAL_ERROR "Unexpected support-profile matrix path")
endif()
set(_matrix_path "${MMXISF_SOURCE_DIR}/${_matrix_relative_path}")
if(NOT EXISTS "${_matrix_path}")
  message(FATAL_ERROR "Support-profile matrix does not exist")
endif()
file(SHA256 "${_matrix_path}" _matrix_actual_sha256)
string(JSON _matrix_expected_sha256 GET "${_profile}" matrix sha256)
if(NOT _matrix_expected_sha256 MATCHES "^[0-9a-f][0-9a-f]+$")
  message(FATAL_ERROR "Invalid support-profile matrix SHA-256")
endif()
string(LENGTH "${_matrix_expected_sha256}" _matrix_sha_length)
if(NOT _matrix_sha_length EQUAL 64)
  message(FATAL_ERROR "Support-profile matrix SHA-256 must have 64 digits")
endif()
if(NOT _matrix_actual_sha256 STREQUAL _matrix_expected_sha256)
  message(FATAL_ERROR "Support-profile matrix SHA-256 mismatch")
endif()

file(READ "${_matrix_path}" _matrix)
string(JSON _row_count LENGTH "${_matrix}" rows)
if(_row_count LESS 1)
  message(FATAL_ERROR "Conformance matrix is empty")
endif()
set(_matrix_ids)
math(EXPR _last_row "${_row_count} - 1")
foreach(_index RANGE ${_last_row})
  string(JSON _id GET "${_matrix}" rows ${_index} id)
  list(FIND _matrix_ids "${_id}" _existing_matrix_index)
  if(NOT _existing_matrix_index EQUAL -1)
    message(FATAL_ERROR "Duplicate conformance-matrix row: ${_id}")
  endif()
  list(APPEND _matrix_ids "${_id}")
endforeach()

set(_profile_ids)
foreach(_disposition REQUIRED INSPECT_ONLY REJECT_EXPLICITLY DEFERRED)
  string(JSON _disposition_type TYPE "${_profile}" dispositions
    ${_disposition})
  if(NOT _disposition_type STREQUAL "ARRAY")
    message(FATAL_ERROR
      "Support-profile disposition ${_disposition} must be an array")
  endif()
  string(JSON _count LENGTH "${_profile}" dispositions ${_disposition})
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE ${_last})
      string(JSON _id GET "${_profile}" dispositions ${_disposition}
        ${_index})
      list(FIND _matrix_ids "${_id}" _matrix_index)
      if(_matrix_index EQUAL -1)
        message(FATAL_ERROR "Unknown support-profile row: ${_id}")
      endif()
      list(FIND _profile_ids "${_id}" _profile_index)
      if(NOT _profile_index EQUAL -1)
        message(FATAL_ERROR "Duplicate support-profile row: ${_id}")
      endif()
      list(APPEND _profile_ids "${_id}")
    endforeach()
  endif()
endforeach()

foreach(_id IN LISTS _matrix_ids)
  list(FIND _profile_ids "${_id}" _profile_index)
  if(_profile_index EQUAL -1)
    message(FATAL_ERROR "Missing support-profile row: ${_id}")
  endif()
endforeach()
list(LENGTH _profile_ids _profile_row_count)
if(NOT _profile_row_count EQUAL _row_count)
  message(FATAL_ERROR
    "Support profile has ${_profile_row_count} rows; expected ${_row_count}")
endif()

set(_expected_platforms macOS-arm64 Linux-amd64 Windows-amd64)
set(_platforms)
string(JSON _platform_count LENGTH "${_profile}" targetPlatforms)
if(NOT _platform_count EQUAL 3)
  message(FATAL_ERROR "Support profile requires exactly three target platforms")
endif()
math(EXPR _last_platform "${_platform_count} - 1")
foreach(_index RANGE ${_last_platform})
  string(JSON _platform GET "${_profile}" targetPlatforms ${_index})
  list(FIND _expected_platforms "${_platform}" _expected_platform_index)
  if(_expected_platform_index EQUAL -1)
    message(FATAL_ERROR "Unexpected support-profile platform: ${_platform}")
  endif()
  list(FIND _platforms "${_platform}" _platform_index)
  if(NOT _platform_index EQUAL -1)
    message(FATAL_ERROR "Duplicate support-profile platform: ${_platform}")
  endif()
  list(APPEND _platforms "${_platform}")
endforeach()

string(JSON _abi_policy GET "${_profile}" productBoundary abiPolicy)
if(NOT _abi_policy STREQUAL "NO_ABI_PROMISE_BEFORE_1.0")
  message(FATAL_ERROR "Unexpected ABI policy: ${_abi_policy}")
endif()
string(JSON _limitation_count LENGTH "${_profile}" limitations)
if(_limitation_count LESS 1)
  message(FATAL_ERROR "Support profile requires explicit limitations")
endif()

message(STATUS
  "Validated ${_profile_id} (${_state}) with ${_profile_row_count} rows")
