cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED MMXISF_SOURCE_DIR)
  message(FATAL_ERROR "MMXISF_SOURCE_DIR is required")
endif()

if(DEFINED MMXISF_READINESS_FILE)
  set(_readiness_path "${MMXISF_READINESS_FILE}")
else()
  set(_readiness_path "${MMXISF_SOURCE_DIR}/docs/production-readiness.json")
endif()
if(NOT EXISTS "${_readiness_path}")
  message(FATAL_ERROR "Missing production readiness ledger: ${_readiness_path}")
endif()
file(READ "${_readiness_path}" _readiness_json)

function(mmxisf_readiness_json_get output)
  string(JSON _value ERROR_VARIABLE _error GET "${_readiness_json}" ${ARGN})
  if(NOT _error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Invalid readiness JSON at ${ARGN}: ${_error}")
  endif()
  set(${output} "${_value}" PARENT_SCOPE)
endfunction()

mmxisf_readiness_json_get(_schema schemaVersion)
if(NOT _schema STREQUAL "2")
  message(FATAL_ERROR "Production readiness schemaVersion must be 2")
endif()

mmxisf_readiness_json_get(_candidate_state candidate state)
mmxisf_readiness_json_get(_candidate_ref candidate ref)
if(NOT _candidate_state MATCHES "^(UNFROZEN|FROZEN)$")
  message(FATAL_ERROR "Candidate state must be UNFROZEN or FROZEN")
endif()
if(_candidate_state STREQUAL "FROZEN")
  if(NOT _candidate_ref MATCHES
     "^v[0-9]+\\.[0-9]+\\.[0-9]+-rc\\.[1-9][0-9]*$")
    message(FATAL_ERROR
      "A frozen candidate requires an immutable vX.Y.Z-rc.N ref")
  endif()
elseif(NOT _candidate_ref STREQUAL "")
  message(FATAL_ERROR "An unfrozen candidate must not claim a ref")
endif()

if(DEFINED MMXISF_SUPPORT_PROFILE_FILE)
  set(_support_profile_path "${MMXISF_SUPPORT_PROFILE_FILE}")
else()
  set(_support_profile_path
    "${MMXISF_SOURCE_DIR}/docs/support-profile-0.1.0.json")
endif()
if(NOT EXISTS "${_support_profile_path}")
  message(FATAL_ERROR "Missing support profile: ${_support_profile_path}")
endif()
file(READ "${_support_profile_path}" _support_profile_json)
string(JSON _profile_state ERROR_VARIABLE _profile_state_error GET
  "${_support_profile_json}" state)
string(JSON _profile_candidate_ref ERROR_VARIABLE _profile_ref_error GET
  "${_support_profile_json}" candidateRef)
if(NOT _profile_state_error STREQUAL "NOTFOUND" OR
   NOT _profile_ref_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Invalid candidate identity in support profile")
endif()
if(_candidate_state STREQUAL "UNFROZEN")
  set(_expected_profile_state PREPARED)
else()
  set(_expected_profile_state FROZEN)
endif()
if(NOT _profile_state STREQUAL _expected_profile_state OR
   NOT _profile_candidate_ref STREQUAL _candidate_ref)
  message(FATAL_ERROR
    "Readiness candidate identity does not match the support profile")
endif()

set(_dimensions standaloneBeta standaloneProduction pfiProduction)
foreach(_dimension IN LISTS _dimensions)
  mmxisf_readiness_json_get(_claim claims ${_dimension})
  if(NOT _claim MATCHES "^(NOT_READY|READY)$")
    message(FATAL_ERROR "Claim ${_dimension} must be NOT_READY or READY")
  endif()
  set(_claim_${_dimension} "${_claim}")
  set(_required_${_dimension} 0)
  set(_passed_${_dimension} 0)
  set(_open_${_dimension} "")
endforeach()

string(JSON _gate_count ERROR_VARIABLE _gate_error LENGTH
  "${_readiness_json}" gates)
if(NOT _gate_error STREQUAL "NOTFOUND" OR _gate_count LESS 1)
  message(FATAL_ERROR "Production readiness ledger requires at least one gate")
endif()
math(EXPR _gate_last "${_gate_count} - 1")
set(_gate_ids "")

foreach(_index RANGE 0 ${_gate_last})
  mmxisf_readiness_json_get(_id gates ${_index} id)
  mmxisf_readiness_json_get(_status gates ${_index} status)
  mmxisf_readiness_json_get(_evidence gates ${_index} evidence)
  mmxisf_readiness_json_get(_note gates ${_index} note)
  if(NOT _id MATCHES "^[a-z0-9][a-z0-9.-]+$")
    message(FATAL_ERROR "Invalid readiness gate id: ${_id}")
  endif()
  list(FIND _gate_ids "${_id}" _duplicate_index)
  if(NOT _duplicate_index EQUAL -1)
    message(FATAL_ERROR "Duplicate readiness gate id: ${_id}")
  endif()
  list(APPEND _gate_ids "${_id}")
  if(NOT _status MATCHES "^(PASS|LIMITED|NOT_TESTED|BLOCKED)$")
    message(FATAL_ERROR "Invalid status for readiness gate ${_id}: ${_status}")
  endif()
  if(_evidence STREQUAL "" OR _note STREQUAL "")
    message(FATAL_ERROR "Readiness gate ${_id} requires evidence and note")
  endif()
  if(NOT EXISTS "${MMXISF_SOURCE_DIR}/${_evidence}")
    message(FATAL_ERROR "Readiness gate ${_id} references missing evidence: ${_evidence}")
  endif()

  string(JSON _required_count ERROR_VARIABLE _required_error LENGTH
    "${_readiness_json}" gates ${_index} requiredFor)
  if(NOT _required_error STREQUAL "NOTFOUND" OR _required_count LESS 1)
    message(FATAL_ERROR "Readiness gate ${_id} requires at least one target")
  endif()
  math(EXPR _required_last "${_required_count} - 1")
  set(_gate_dimensions "")
  foreach(_required_index RANGE 0 ${_required_last})
    mmxisf_readiness_json_get(_dimension gates ${_index} requiredFor
      ${_required_index})
    if(NOT _dimension IN_LIST _dimensions)
      message(FATAL_ERROR "Unknown readiness target on ${_id}: ${_dimension}")
    endif()
    if(_dimension IN_LIST _gate_dimensions)
      message(FATAL_ERROR "Duplicate readiness target on ${_id}: ${_dimension}")
    endif()
    list(APPEND _gate_dimensions "${_dimension}")
    math(EXPR _required_${_dimension} "${_required_${_dimension}} + 1")
    if(_status STREQUAL "PASS")
      math(EXPR _passed_${_dimension} "${_passed_${_dimension}} + 1")
    else()
      list(APPEND _open_${_dimension} "${_id}=${_status}")
    endif()
  endforeach()
endforeach()

foreach(_dimension IN LISTS _dimensions)
  set(_derived_claim NOT_READY)
  if(_candidate_state STREQUAL "FROZEN" AND
     _required_${_dimension} EQUAL _passed_${_dimension})
    set(_derived_claim READY)
  endif()
  if(NOT _claim_${_dimension} STREQUAL _derived_claim)
    message(FATAL_ERROR
      "Claim ${_dimension}=${_claim_${_dimension}} conflicts with derived ${_derived_claim}")
  endif()
  list(JOIN _open_${_dimension} ", " _open_text)
  if(_open_text STREQUAL "")
    if(_candidate_state STREQUAL "FROZEN")
      set(_open_text "all required gates pass")
    else()
      set(_open_text "candidate is not frozen")
    endif()
  endif()
  message(STATUS
    "Readiness ${_dimension}: ${_derived_claim} (${_passed_${_dimension}}/${_required_${_dimension}} gates PASS; ${_open_text})")
endforeach()
